apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-deployment
  labels:
    app: regapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: regapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: arunkumarravi08/hello-world:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
spec:
  type: LoadBalancer
  selector:
    app: regapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
